import { Tour } from "nextstepjs";

export const onboardingTour:Tour = {
    tour: "onboarding",
    steps: [
        {
            icon: "👋",
            title: "Welcome to Mesa AI",
            content: "Take a short tour to get familiar with how Mesa AI works.\n\n This tour will take about **2-3 minutes**.",
            showControls: true,
            showSkip: true,
            blockKeyboardControl: true,
        },
        {
            title: "Create your first class",
            icon: "🏫",
            side: 'bottom',
            content: "Classes are where you organise all your materials. Click the button to create one.",
            selector: "#createClassCard",
            showControls: false,
            blockKeyboardControl: true,
        },
        {
            title: "Create your first class",
            icon: "🏫",
            side: 'right',
            content: "Customise your class details here. You can always edit these later. Then, **submit it**.",
            selector: "#createClassDialog",
            showControls: false,
            pointerPadding: 0,
            pointerRadius: 8,
            blockKeyboardControl: true,
        },
        {
            title: "Class basics",
            icon: "📚",
            side: 'right',
            content: "Here is where you can **navigate** between different sections of your class, such as your dashboard, drive, library and topics.",
            selector: "#classSidebar",
            showControls: true,
            pointerPadding: 0,
            pointerRadius: 0,
            disableInteraction: true,
            blockKeyboardControl: true,
        },
        {
            title: "Basics: Mesa Notebooks",
            icon: "📚",
            side: 'right',
            content: "The notebooks page **organises** class materials and resources. Navigate there by **clicking** 'Notebooks'.",
            selector: "#NotebooksTab",
            pointerPadding: 5,
            pointerRadius: 10,
            blockKeyboardControl: true,
        },
        {
            title: "Creating a Notebook",
            icon: "📚",
            side: "bottom-right",
            content: "Create your **first notebook** by clicking the 'Create new' button.",
            selector: "#createNotebookButton",
            pointerPadding: 5,
            pointerRadius: 10,
            blockKeyboardControl: true,
        },
        {
            title: "Welcome to Notebooks!",
            icon: "👋",
            content: "Notebooks are a great way to **consolidate** all your learning materials for a topic. \n\n**Notes** added here can be turned into summary notes, while **quizzes** can test for understanding.",
            showControls: true,
            blockKeyboardControl: true,
        },
        {
            title: "Adding sources",
            icon: "📕",
            side: 'left',
            selector: "#sourcesPanel",
            content: "The sources panel allows you to manage the materials for your topic. \n\nFirstly, try adding a **source** by clicking the '+' button.",
            blockKeyboardControl: true,
            pointerPadding: 10,
            pointerRadius: 8,
        },
        {
            title: "Adding sources",
            icon: "📕",
            side: "right",
            selector: "#fileSelectorDialog",
            content: "The file selector allows you to **choose files** from **Mesa Drive** to add as sources. You can also upload new files here. \n\nTry adding a file using the **'Create new'** button. \n\nDon't have any? [Here's a file you can use](https://raw.githubusercontent.com/ng-qi-an/mesa-ai/refs/heads/master/sample-notes/01.%20intro%20%26%20kinematics.pdf).",
            pointerPadding: 0,
            pointerRadius: 8,
            blockKeyboardControl: true,
        },
        {
            title: "Generating notes",
            icon: "📝",
            side: "right",
            selector: "#notebookPanel",
            content: "This is the notebook panel, where you would be able to see your summarised notes. \n\n To begin, click the **'Generate notes'** button.",
            pointerPadding: 10,
            pointerRadius: 8,
            blockKeyboardControl: true,
        },
        {
            title: "Generating notes",
            icon: "📝",
            side: "right",
            selector: "#generateNotesDialog",
            content: "Customise how you want your notes to be generated. \n\n Afterwards, press **'Generate now'** to begin.",
            pointerPadding: 0,
            pointerRadius: 8,
            blockKeyboardControl: true,
        },
        {
            title: "You're all set!",
            icon: "🎉",
            content: "Thanks for taking the tour! \n\n From here on, you can explore the various features of Mesa AI at your own pace. \n\n **Happy learning!** 🚀",
            showControls: true,
            blockKeyboardControl: true,
        },
    ]
};
